### ISSUE TITLE
Allow Options upon Init

### ISSUE THREAD

**Issue by parkr** [incandescent/mbt#1]
Proposed options:
- `--coffee` to write output in CoffeeScript
- `--jqm` to include jQuery Mobile
- `--spine` to use Spine.js as framework
- `--backbone` to use Backbone.js as framework

**Comment by mkuklis** [comment]
I think I like this :) I will see how hard it will be to customize it to support this ;)

**Comment by mkuklis** [comment]
@parkr this should be somehow supported now for coffeescript with
    mbt init:project:coffee

I still have to review how to handle other dependencies. I think for now you can replace them by hand.

**Comment by parkr** [comment]
@mkuklis @ahamid I just reinstalled the latest version of mbt for a new project. Is there a quick way to use CoffeeScript instead of JS? (I didn't see `mbt init:project:coffee`). Maybe re-create a new app with that command and copy over `.coffee` files?

**Comment by parkr** [comment]
Just tried `mbt init:project:coffee` and it did not generate `.coffee` files.

**Comment by mkuklis** [comment]
Will look into this tonight. Sorry it didn't work for you. Michal

**Comment by parkr** [comment]
No problem! I just copied over the `app/js` folder and converted the needed files to CoffeeScript. All set to go!

**Comment by mkuklis** [comment]
@parkr finally had a chance to look into this. I haven't really changed anything. I think we forgot to publish new version via npm in the past. If you want to grab new version you will have to uninstall previous version first `npm uninstall mbt` or if you installed it globally `npm uninstall mbt -g`. The mbt is on 0.1.1 now.

**Comment by parkr** [comment]
Got it. Won't `npm update` achieve this?

**Comment by mkuklis** [comment]
I think normally `npm update` should work but we were pushing the same version to the npm repo with `npm publish --force`. I changed the version to 0.1.1 yesterday so please go ahead and try `npm update` and see what happens.

**Comment by parkr** [comment]
Both `npm update` and `npm update mbt` exited without any indication that an update took place. I'll uninstall and reinstall mbt.

**Comment by mkuklis** [comment]
closing this for now.
