### ISSUE TITLE
Add Optional CoffeeScript Compiler

### ISSUE THREAD

**Issue by parkr** [incandescent/mbt#2]
`mbt watch` would compile `*.coffee` files found in subdirectories into JavaScript files.

**Comment by mkuklis** [comment]
+1

**Comment by mkuklis** [comment]
this should be now in place. You will have to install mbt again and generate new project with:
    mbt init:project:coffee

Please let us know if you run into any issues. We don't have versioning or testing in place yet but will look into it.
